import { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowRight, Award, Check, ChevronLeft, Crosshair, Flame, Gamepad2, Home, Link, LogOut, ScrollText, Sparkles, Swords, Trophy, UserRound, X } from 'lucide-react';
import './styles.css';
import './connection.css';

const API = `${(import.meta.env.VITE_API_URL || 'http://localhost:4000').replace(/\/$/, '')}/api`;
function storedUser() {
  try { return JSON.parse(localStorage.getItem('questup-user') || 'null'); }
  catch { localStorage.removeItem('questup-user'); return null; }
}

async function request(path, options = {}) {
  const response = await fetch(`${API}${path}`, { headers: { 'Content-Type': 'application/json', ...(options.token ? { Authorization: `Bearer ${options.token}` } : {}) }, ...options });
  const data = await response.json();
  if (!response.ok) throw new Error(data.message || 'เกิดข้อผิดพลาด');
  return data;
}

function App() {
  const [token, setToken] = useState(localStorage.getItem('questup-token'));
  const [user, setUser] = useState(storedUser);
  const [view, setView] = useState('home');
  const [selectedQuest, setSelectedQuest] = useState(null);
  const [dashboard, setDashboard] = useState(null);
  const [error, setError] = useState('');
  useEffect(() => { if (token) request('/dashboard', { token }).then(setDashboard).catch(() => logout()); }, [token]);
  function login(result) { localStorage.setItem('questup-token', result.token); localStorage.setItem('questup-user', JSON.stringify(result.user)); setToken(result.token); setUser(result.user); }
  function logout() { localStorage.clear(); setToken(null); setUser(null); setDashboard(null); }
  async function completeQuest(id) { try { const updated = await request(`/quests/${id}/complete`, { method: 'PATCH', token }); const refreshed = await request('/dashboard', { token }); setDashboard(refreshed); setUser(refreshed.user); localStorage.setItem('questup-user', JSON.stringify(refreshed.user)); setSelectedQuest(updated); } catch (err) { setError(err.message); } }
  async function connectGame(gameId, playerId) { const result = await request('/games/connect', { method: 'POST', token, body: JSON.stringify({ gameId, playerId }) }); setDashboard(await request('/dashboard', { token })); setError(result.message); }
  async function addQuest(quest) { const result = await request('/quests', { method: 'POST', token, body: JSON.stringify(quest) }); setDashboard(await request('/dashboard', { token })); setError(result.message); }
  if (!token || !dashboard) return <AuthScreen onLogin={login} setError={setError} />;
  if (!dashboard.games.length) return <Shell user={user} view="profile" setView={setView} logout={logout}><ConnectGameView connectGame={connectGame} setError={setError} /></Shell>;
  return <Shell user={user} view={view} setView={setView} logout={logout}>
    {view === 'home' && <HomeView data={dashboard} onOpenQuest={quest => { setSelectedQuest(quest); setView('quest-detail'); }} setView={setView} />}
    {view === 'game' && <GameView game={dashboard.games[0]} quests={dashboard.quests} setView={setView} onOpenQuest={quest => { setSelectedQuest(quest); setView('quest-detail'); }} />}
    {view === 'quests' && <QuestView quests={dashboard.quests} gameId={dashboard.games[0].id} onOpenQuest={quest => { setSelectedQuest(quest); setView('quest-detail'); }} onAddQuest={addQuest} setError={setError} />}
    {view === 'quest-detail' && <QuestDetail quest={selectedQuest || dashboard.quests[0]} onBack={() => setView('quests')} onComplete={completeQuest} />}
    {view === 'achievements' && <AchievementView achievements={dashboard.achievements} />}
    {view === 'profile' && <ProfileView user={user} games={dashboard.games} gameAccounts={dashboard.gameAccounts} connectGame={connectGame} setError={setError} logout={logout} />}
    {error && <button className="toast" onClick={() => setError('')}>{error}<X size={15} /></button>}
  </Shell>;
}

function AuthScreen({ onLogin, setError }) {
  const [mode, setMode] = useState('register'); const [form, setForm] = useState({ name: '', email: '', password: '' }); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(event) { event.preventDefault(); setBusy(true); setError(''); setMessage(''); try { if (mode === 'forgot') { const result = await request('/auth/forgot-password', { method: 'POST', body: JSON.stringify({ email: form.email }) }); setMessage(result.message); } else if (mode === 'register') { await request('/auth/register', { method: 'POST', body: JSON.stringify(form) }); onLogin(await request('/auth/login', { method: 'POST', body: JSON.stringify({ email: form.email, password: form.password }) })); } else { onLogin(await request('/auth/login', { method: 'POST', body: JSON.stringify(form) })); } } catch (err) { setError(err.message); } finally { setBusy(false); } }
  return <main className="auth-page"><div className="auth-art"><div className="brand-mark"><Swords size={22} /> QUESTUP</div><div className="orb orb-one" /><div className="orb orb-two" /><div className="auth-copy"><span className="eyebrow">YOUR ADVENTURE, ORGANIZED</span><h1>Make every quest<br /><em>count.</em></h1><p>Track the worlds you play, the missions you conquer, and the legend you are becoming.</p><div className="auth-stat"><Flame size={18} /><strong>12 day streak</strong><span>keep the run alive</span></div></div></div><section className="auth-form"><div className="mobile-brand"><Swords size={20} /> QUESTUP</div><span className="eyebrow">{mode === 'login' ? 'WELCOME BACK' : mode === 'register' ? 'JOIN THE PARTY' : 'ACCOUNT RECOVERY'}</span><h2>{mode === 'login' ? 'Sign in to your hub' : mode === 'register' ? 'Create your legend' : 'Find your way back'}</h2><p className="muted">{mode === 'forgot' ? 'Enter your email and we will send recovery instructions.' : 'Your quests are waiting on the other side.'}</p><form onSubmit={submit}>{mode === 'register' && <label>Display name<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="Your adventurer name" /></label>}<label>Email<input required type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /></label>{mode !== 'forgot' && <label>Password<input required minLength="6" type="password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} /></label>}<button className="primary-button" disabled={busy}>{busy ? 'Loading...' : mode === 'login' ? 'Enter QuestUp' : mode === 'register' ? 'Create account' : 'Send recovery email'} <ArrowRight size={17} /></button></form>{message && <div className="success-message"><Check size={16} /> {message}</div>}<div className="auth-switch">{mode === 'login' && <button onClick={() => setMode('forgot')}>Forgot password?</button>}<button onClick={() => setMode(mode === 'login' ? 'register' : 'login')}>{mode === 'login' ? 'New to QuestUp? Create account' : 'Already have an account? Sign in'}</button></div><small className="demo-note">Demo access: demo@questup.app / questup123</small></section></main>;
}

function Shell({ user, view, setView, logout, children }) { const nav = [['home', Home, 'Home'], ['quests', ScrollText, 'Quests'], ['achievements', Trophy, 'Achievements'], ['profile', UserRound, 'Profile']]; return <div className="app-shell"><aside><div className="brand-mark"><Swords size={21} /> QUESTUP</div><div className="side-label">YOUR HUB</div><nav>{nav.map(([id, Icon, label]) => <button className={view === id ? 'active' : ''} key={id} onClick={() => setView(id)}><Icon size={18} /> {label}</button>)}</nav><div className="side-bottom"><div className="mini-user"><div className="avatar">MC</div><div><strong>{user.name}</strong><small>Level {user.level}</small></div></div><button className="icon-button" title="Sign out" onClick={logout}><LogOut size={17} /></button></div></aside><main className="content"><header><div><span className="eyebrow">MONDAY, 24 AUGUST 2026</span><h2>{view === 'home' ? 'Good evening, Mira.' : nav.find(item => item[0] === view)?.[2] || 'Quest detail'}</h2></div><div className="header-actions"><div className="avatar">MC</div></div></header>{children}</main><div className="mobile-nav">{nav.map(([id, Icon, label]) => <button className={view === id ? 'active' : ''} key={id} onClick={() => setView(id)}><Icon size={18} /><small>{label}</small></button>)}</div></div>; }

function HomeView({ data, onOpenQuest, setView }) { const active = data.quests.filter(q => q.status !== 'completed'); return <div className="view-stack"><section className="hero-panel"><div><span className="eyebrow lime">ACTIVE ADVENTURE</span><h1>Keep the momentum.</h1><p>Three missions are calling your name today.</p><button className="dark-button" onClick={() => setView('quests')}>View all quests <ArrowRight size={16} /></button></div><div className="hero-sigil"><Crosshair size={62} strokeWidth={1.2} /></div></section><div className="metric-grid"><Metric icon={<Flame />} label="Day streak" value={`${data.user.streak} days`} detail="Personal best: 18" /><Metric icon={<Sparkles />} label="Total XP" value={data.user.xp.toLocaleString()} detail="+420 this week" /><Metric icon={<Trophy />} label="Achievements" value={`${data.achievements.filter(a => a.unlocked).length}/${data.achievements.length}`} detail="Keep collecting" /></div><section className="section-heading"><div><span className="eyebrow">CURRENT WORLD</span><h3>Your adventures</h3></div><button className="text-button" onClick={() => setView('game')}>Open details <ArrowRight size={15} /></button></section><button className="game-card" onClick={() => setView('game')}><div className="game-icon">✦</div><div className="game-info"><span>OPEN WORLD RPG</span><h3>{data.games[0].name}</h3><div className="progress-line"><i style={{ width: `${data.games[0].progress}%` }} /></div><small>Level {data.games[0].level} <b>{data.games[0].progress}% explored</b></small></div><ChevronLeft className="rotate" size={20} /></button><section className="section-heading"><div><span className="eyebrow">UP NEXT</span><h3>Priority quests</h3></div><span className="count-pill">{active.length} active</span></section><div className="quest-list">{active.slice(0, 2).map(quest => <QuestRow key={quest.id} quest={quest} onClick={() => onOpenQuest(quest)} />)}</div></div>; }
function Metric({ icon, label, value, detail }) { return <div className="metric"><div className="metric-icon">{icon}</div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div>; }
function QuestRow({ quest, onClick }) { return <button className="quest-row" onClick={onClick}><div className={`quest-type ${quest.type === 'Epic quest' ? 'epic' : ''}`}><Swords size={17} /></div><div className="quest-row-copy"><span>{quest.type} <b>· {quest.due}</b></span><h4>{quest.title}</h4><div className="progress-line"><i style={{ width: `${quest.progress}%` }} /></div></div><strong className="reward">+{quest.reward} XP</strong><ArrowRight size={17} /></button>; }
function GameView({ game, quests, setView, onOpenQuest }) { return <div className="view-stack detail-view"><button className="back-button" onClick={() => setView('home')}><ChevronLeft size={17} /> Back to home</button><div className="game-banner"><div className="game-icon large">✦</div><div><span className="eyebrow">ADVENTURE PROFILE</span><h1>{game.name}</h1><p>{game.genre} <span className="dot">●</span> Last played today</p></div><button className="primary-button compact" onClick={() => setView('quests')}>View quests <ArrowRight size={16} /></button></div><div className="metric-grid three"><Metric icon={<Crosshair />} label="Quests completed" value={quests.filter(quest => quest.status === 'completed').length} detail={`of ${quests.length} total`} /><Metric icon={<Award />} label="World level" value={game.level} detail={`${game.progress}% explored`} /><Metric icon={<Gamepad2 />} label="Play time" value="128h" detail="This season" /></div><section className="section-heading"><div><span className="eyebrow">RECENT MISSIONS</span><h3>Quest activity</h3></div></section><div className="quest-list">{quests.map(quest => <QuestRow key={quest.id} quest={quest} onClick={() => onOpenQuest(quest)} />)}</div></div>; }
function QuestView({ quests, gameId, onOpenQuest, onAddQuest, setError }) { const [filter, setFilter] = useState('All quests'); const [showForm, setShowForm] = useState(false); const [form, setForm] = useState({ title: '', description: '', reward: 100 }); async function submit(event) { event.preventDefault(); try { await onAddQuest({ ...form, gameId, reward: Number(form.reward) }); setForm({ title: '', description: '', reward: 100 }); setShowForm(false); } catch (err) { setError(err.message); } } return <div className="view-stack"><div className="filter-bar">{['All quests', 'Active', 'Completed'].map(item => <button className={filter === item ? 'selected' : ''} onClick={() => setFilter(item)} key={item}>{item}</button>)}<button className="dark-button" onClick={() => setShowForm(value => !value)}>{showForm ? 'Close' : 'Add quest'}</button></div>{showForm && <form className="connect-inline" onSubmit={submit}><input required value={form.title} onChange={event => setForm({ ...form, title: event.target.value })} placeholder="Quest title" /><input required value={form.description} onChange={event => setForm({ ...form, description: event.target.value })} placeholder="Description" /><input required min="1" type="number" value={form.reward} onChange={event => setForm({ ...form, reward: event.target.value })} placeholder="XP reward" /><button className="primary-button">Save quest</button></form>}<div className="quest-list full">{quests.filter(q => filter === 'All quests' || (filter === 'Active' ? q.status !== 'completed' : q.status === 'completed')).map(quest => <QuestRow key={quest.id} quest={quest} onClick={() => onOpenQuest(quest)} />)}</div></div>; }
function QuestDetail({ quest, onBack, onComplete }) { return <div className="view-stack detail-view"><button className="back-button" onClick={onBack}><ChevronLeft size={17} /> Back to quests</button><div className="quest-detail-head"><div className="quest-type epic big"><Swords size={31} /></div><div><span className="eyebrow">{quest.type}</span><h1>{quest.title}</h1><p>{quest.description}</p></div></div><div className="detail-card"><div className="detail-card-top"><span>MISSION PROGRESS</span><strong>{quest.progress}%</strong></div><div className="progress-line tall"><i style={{ width: `${quest.progress}%` }} /></div><div className="detail-facts"><span>Reward <b>{quest.reward} XP</b></span><span>Due <b>{quest.due}</b></span><span>Status <b>{quest.status}</b></span></div></div><button className={`primary-button ${quest.status === 'completed' ? 'complete' : ''}`} disabled={quest.status === 'completed'} onClick={() => onComplete(quest.id)}>{quest.status === 'completed' ? <><Check size={18} /> Quest completed</> : <>Complete quest <ArrowRight size={17} /></>}</button></div>; }
function AchievementView({ achievements }) { return <div className="view-stack"><div className="achievement-summary"><div><span className="eyebrow lime">COLLECTION PROGRESS</span><h1>Small wins. Big legend.</h1></div><strong>{achievements.filter(a => a.unlocked).length}<small> / {achievements.length} unlocked</small></strong></div><div className="achievement-grid">{achievements.map(item => <div className={`achievement ${item.unlocked ? '' : 'locked'}`} key={item.id}><div className="achievement-icon">{item.unlocked ? item.icon : '🔒'}</div><h3>{item.title}</h3><p>{item.description}</p><span>{item.unlocked ? 'UNLOCKED' : 'LOCKED'}</span></div>)}</div></div>; }
function ConnectGameView({ connectGame, setError }) { const [gameId, setGameId] = useState('genshin'); const [playerId, setPlayerId] = useState(''); const [busy, setBusy] = useState(false); async function submit(event) { event.preventDefault(); setBusy(true); setError(''); try { await connectGame(gameId, playerId); } catch (err) { setError(err.message); } finally { setBusy(false); } } return <div className="connect-page"><div className="connect-icon"><Link size={31} /></div><span className="eyebrow lime">ONE LAST STEP</span><h1>Connect your first game.</h1><p>QuestUp จะใช้ Player ID เพื่อดึงและจัดกลุ่มภารกิจของเกมนั้นให้คุณ บัญชีเกมจะไม่ถูกเก็บรหัสผ่าน</p><form onSubmit={submit} className="connect-form"><label>เลือกเกม<select value={gameId} onChange={event => setGameId(event.target.value)}><option value="genshin">Genshin Adventure</option><option value="stardew">Stardew Valley</option><option value="valorant">VALORANT</option></select></label><label>Player ID<input required value={playerId} onChange={event => setPlayerId(event.target.value)} placeholder="เช่น UID หรือ Riot ID" /></label><button className="primary-button" disabled={busy}>{busy ? 'กำลังเชื่อมต่อ...' : 'เชื่อมต่อเกม'} <ArrowRight size={17} /></button></form></div>; }
function ProfileView({ user, games, gameAccounts, connectGame, setError, logout }) { const [gameId, setGameId] = useState('genshin'); const [playerId, setPlayerId] = useState(''); const [busy, setBusy] = useState(false); async function submit(event) { event.preventDefault(); setBusy(true); setError(''); try { await connectGame(gameId, playerId); setPlayerId(''); } catch (err) { setError(err.message); } finally { setBusy(false); } } return <div className="view-stack profile-view"><div className="profile-hero"><div className="profile-avatar">MC</div><div><span className="eyebrow lime">PLAYER PROFILE</span><h1>{user.name}</h1><p>Joined August 2026 <span className="dot">●</span> {user.role === 'admin' ? 'Administrator' : 'Adventurer'}</p></div><span className="level-badge">LV. {user.level}</span></div><div className="profile-stats"><div><span>XP earned</span><strong>{user.xp.toLocaleString()}</strong></div><div><span>Quest coins</span><strong>{user.coins.toLocaleString()}</strong></div><div><span>Best streak</span><strong>18 days</strong></div></div><section className="connected-games"><div className="section-heading"><div><span className="eyebrow">GAME CONNECTIONS</span><h3>เกมของคุณ</h3></div><span className="count-pill">{games.length} connected</span></div>{games.map(game => <div className="connected-game" key={game.id}><div className="game-icon" style={{ background: game.color }}>{game.icon}</div><div><strong>{game.name}</strong><small>{gameAccounts.find(account => account.gameId === game.id)?.playerId || 'Connected account'}</small></div><Check size={17} /></div>)}<form className="connect-inline" onSubmit={submit}><select value={gameId} onChange={event => setGameId(event.target.value)}><option value="genshin">Genshin Adventure</option><option value="stardew">Stardew Valley</option><option value="valorant">VALORANT</option></select><input required value={playerId} onChange={event => setPlayerId(event.target.value)} placeholder="Player ID" /><button className="dark-button" disabled={busy}>Add game</button></form></section><button className="danger-action" onClick={logout}><LogOut size={18} /> Sign out <ArrowRight size={16} /></button></div>; }

createRoot(document.getElementById('root')).render(<App />);
